# Generated by Django 3.1.2 on 2020-12-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0016_auto_20201203_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcomponentsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=300)),
                ('path', models.CharField(default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='', max_length=200)),
                ('originalAmount', models.FloatField(default=0)),
                ('creationTime', models.TimeField()),
                ('availableAmount', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('parentFolder', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rawMaterialsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=300)),
                ('path', models.CharField(default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='', max_length=200)),
                ('originalAmount', models.FloatField(default=0)),
                ('units', models.CharField(default='', max_length=300)),
                ('availableAmount', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('serialNumber', models.CharField(default='', max_length=300)),
                ('provider', models.CharField(default='', max_length=300)),
                ('parentFolder', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='equipmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=300)),
                ('path', models.CharField(default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('productivity', models.FloatField(default=0)),
                ('exploitationCost', models.FloatField(default=0)),
                ('serialNumber', models.CharField(default='', max_length=300)),
                ('provider', models.CharField(default='', max_length=300)),
                ('parentFolder', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
