# Generated by Django 3.2.8 on 2021-10-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20211012_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.provider'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.provider'),
        ),
    ]
