# Generated by Django 3.2.8 on 2021-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20211013_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttable',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterialstable',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcomponentstable',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
