# Generated by Django 3.2.8 on 2021-11-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20211026_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='measurementUnitTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=300)),
                ('path', models.CharField(default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.measurementunittable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='organisationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=300)),
                ('path', models.CharField(default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('address', models.CharField(max_length=500)),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.organisationtable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='statusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=300)),
                ('path', models.CharField(default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.statustable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='equipmenttable',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='equipmenttable',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='rawmaterialstable',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='rawmaterialstable',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='subcomponentstable',
            name='approved',
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rawmaterialstable',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subcomponentstable',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='provider',
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.organisationtable'),
        ),
        migrations.AddField(
            model_name='rawmaterialstable',
            name='measurementUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.measurementunittable'),
        ),
        migrations.AddField(
            model_name='rawmaterialstable',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.organisationtable'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.statustable'),
        ),
    ]
