# Generated by Django 3.2.8 on 2021-11-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20211118_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.equipmenttable'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.rawmaterialstable'),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.subcomponentstable'),
        ),
    ]
