# Generated by Django 3.2.8 on 2021-11-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_alter_excelfolder_parentfolder'),
        ('tables', '0009_auto_20211127_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
    ]
