# Generated by Django 4.0 on 2022-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20211127_1928'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rawmaterialstable',
        #     name='units',
        # ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
