# Generated by Django 4.0 on 2022-01-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_remove_rawmaterialstable_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialstable',
            name='units',
        ),
    ]
