# Generated by Django 4.0 on 2022-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_remove_rawmaterialstable_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
    ]
