# Generated by Django 4.0 on 2022-02-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_equipmenttable_updatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tables.statustable'),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tables.statustable'),
        ),
    ]
