# Generated by Django 4.0 on 2022-02-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tables', '0015_alter_rawmaterialstable_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('UID', models.CharField(default='', max_length=10)),
                ('tableName', models.CharField(blank=True, default='', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.departmenttable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='UID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='UID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='measurementunittable',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='UID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='organisationtable',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='UID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='UID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='UID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='tableName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='documentTypeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('UID', models.CharField(default='', max_length=10)),
                ('tableName', models.CharField(blank=True, default='', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.documenttypetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='documentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, default='ghost', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('UID', models.CharField(default='', max_length=10)),
                ('tableName', models.CharField(blank=True, default='', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('checkUntil', models.DateTimeField(blank=True, null=True)),
                ('approveUntil', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('coAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coAuthor', to='auth.user')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.departmenttable')),
                ('documentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.documenttypetable')),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.documenttable')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.departmenttable'),
        ),
        migrations.AddField(
            model_name='rawmaterialstable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.departmenttable'),
        ),
        migrations.AddField(
            model_name='subcomponentstable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.departmenttable'),
        ),
    ]
