# Generated by Django 4.0 on 2022-02-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_alter_excelfile_author_alter_excelfolder_uid_and_more'),
        ('tables', '0017_remove_departmenttable_parentfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
        migrations.AddField(
            model_name='documenttable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
        migrations.AddField(
            model_name='documenttypetable',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
    ]
