# Generated by Django 3.1.2 on 2020-11-08 19:50

from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URIlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='subcomponentsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=100)),
                ('path', models.CharField(default='prFold', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=200)),
                ('originalAmount', models.FloatField(default=0)),
                ('creationTime', models.TimeField()),
                ('availableAmount', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('parentFolder', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='general.subcomponentstable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rawMaterialsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=100)),
                ('path', models.CharField(default='prFold', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=200)),
                ('originalAmount', models.FloatField(default=0)),
                ('units', models.CharField(default='', max_length=300)),
                ('availableAmount', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('serialNumber', models.CharField(default='', max_length=300)),
                ('provider', models.CharField(default='', max_length=300)),
                ('parentFolder', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='general.rawmaterialstable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='excelFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=100)),
                ('path', models.CharField(default='prFold', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('parentFolder', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='excelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=general.models.contentFileName)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(default='prFold', max_length=500)),
                ('UID', models.CharField(default='', max_length=300)),
                ('fileFolder', models.ForeignKey(default=107, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder')),
            ],
        ),
        migrations.CreateModel(
            name='equipmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='No author', max_length=100)),
                ('path', models.CharField(default='prFold', max_length=300)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(default='', max_length=300)),
                ('tableName', models.CharField(default='', max_length=300)),
                ('productivity', models.FloatField(default=0)),
                ('exploitationCost', models.FloatField(default=0)),
                ('serialNumber', models.CharField(default='', max_length=300)),
                ('provider', models.CharField(default='', max_length=300)),
                ('parentFolder', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='general.equipmenttable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
