# Generated by Django 3.1.2 on 2020-11-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttable',
            name='parentFolder',
        ),
        migrations.RemoveField(
            model_name='excelfolder',
            name='parentFolder',
        ),
        migrations.RemoveField(
            model_name='rawmaterialstable',
            name='parentFolder',
        ),
        migrations.RemoveField(
            model_name='subcomponentstable',
            name='parentFolder',
        ),
    ]
