# Generated by Django 3.1.2 on 2020-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20201108_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='path',
            field=models.CharField(default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='excelfolder',
            name='path',
            field=models.CharField(default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='path',
            field=models.CharField(default='ghost', max_length=300),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='path',
            field=models.CharField(default='ghost', max_length=300),
        ),
    ]
