# Generated by Django 3.1.2 on 2020-11-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20201108_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='parentFolder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='parentFolder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder'),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='parentFolder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='general.excelfolder'),
        ),
    ]
