# Generated by Django 3.1.2 on 2020-11-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20201109_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URIlist',
            new_name='UIDlist',
        ),
        migrations.RemoveField(
            model_name='equipmenttable',
            name='exploitationCost',
        ),
    ]
