# Generated by Django 3.1.2 on 2020-12-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_equipmenttable_exploitationcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='author',
            field=models.CharField(default='No author', max_length=300),
        ),
        migrations.AlterField(
            model_name='excelfolder',
            name='author',
            field=models.CharField(default='No author', max_length=300),
        ),
        migrations.AlterField(
            model_name='rawmaterialstable',
            name='author',
            field=models.CharField(default='No author', max_length=300),
        ),
        migrations.AlterField(
            model_name='subcomponentstable',
            name='author',
            field=models.CharField(default='No author', max_length=300),
        ),
    ]
