# Generated by Django 3.1.2 on 2020-12-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20201201_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttable',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excelfolder',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterialstable',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcomponentstable',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uidlist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
