# Generated by Django 3.1.2 on 2020-12-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_remove_uidlist_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialstable',
            name='parentFolder',
        ),
        migrations.RemoveField(
            model_name='subcomponentstable',
            name='parentFolder',
        ),
        migrations.DeleteModel(
            name='equipmentTable',
        ),
        migrations.DeleteModel(
            name='rawMaterialsTable',
        ),
        migrations.DeleteModel(
            name='subcomponentsTable',
        ),
    ]
