# Generated by Django 3.1.2 on 2020-12-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20201203_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='fileFolder',
        ),
    ]
