# Generated by Django 3.1.2 on 2020-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_remove_excelfile_filefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='additionalInfo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
