# Generated by Django 3.2.8 on 2021-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_excelfile_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfolder',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
