# Generated by Django 3.2.8 on 2021-11-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_excelfolder_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfolder',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.excelfolder'),
        ),
    ]
