# Generated by Django 3.2.8 on 2021-11-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_alter_excelfolder_parentfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfolder',
            name='approved',
        ),
        migrations.AddField(
            model_name='excelfolder',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
