# Generated by Django 3.2.8 on 2021-11-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20211118_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfolder',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
    ]
