# Generated by Django 4.0 on 2022-01-21 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_alter_excelfolder_description_alter_excelfolder_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.excelfolder'),
        ),
    ]
