# Generated by Django 4.0 on 2022-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_alter_excelfolder_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfolder',
            name='path',
            field=models.CharField(blank=True, default='ghost', max_length=300),
        ),
    ]
