# Generated by Django 4.0 on 2022-02-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_excelfile_parentfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='parentFolder',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='parentFolderUID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='UID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
